### ISSUE TITLE
Nord theme for Image Glass

### ISSUE THREAD

**Issue by SleepyMatt** [ImageGlass/theme#10]
Preview
![preview](https://user-images.githubusercontent.com/109416367/179353103-5831c779-07a1-421c-8f16-f08912de454e.jpg)

Downloads are available as zip, igtheme and all files [**here**](https://github.com/SleepyMatt/imageglass-themes/tree/main/Nord-Theme-Dark.SleepyMatt)

[Zip](https://github.com/SleepyMatt/imageglass-themes/tree/main/Nord-Theme-Dark.SleepyMatt/zip)
[Igtheme](https://github.com/SleepyMatt/imageglass-themes/tree/main/Nord-Theme-Dark.SleepyMatt/.igtheme)
[All files](https://github.com/SleepyMatt/imageglass-themes/tree/main/Nord-Theme-Dark.SleepyMatt/all-files)

**Comment by SleepyMatt** [comment]
https://github.com/SleepyMatt/imageglass-themes

**Comment by d2phap** [comment]
Hi @SleepyMatt 

Can you
- rename your theme pack from `Nord Theme (Dark).igtheme` to `Nord-Theme-Dark.SleepyMatt.igtheme`, and
- the theme folder from `Nord Theme (Dark)` to `Nord-Theme-Dark.SleepyMatt`?

It's recommended to follow to naming convention: https://github.com/ImageGlass/theme#-naming-convention

**Comment by d2phap** [comment]
And also, rename `config.xml` to `igtheme.xml` according to the Folder structure: https://github.com/ImageGlass/theme#-theme-pack-folder-structure

**Comment by SleepyMatt** [comment]
Hi @d2phap can you check if everything is correct now? I already updated the links on the first comment.

**Comment by d2phap** [comment]
Thanks @SleepyMatt 
Here is the link: https://imageglass.org/theme/Nord-Theme-Dark-SleepyMatt-47

FYI, I use this file for the screenshot and thumbnail on IG website: https://github.com/SleepyMatt/imageglass-themes/blob/main/Nord-Theme-Dark.SleepyMatt/all-files/preview.jpg

And this file for download: https://github.com/SleepyMatt/imageglass-themes/blob/main/Nord-Theme-Dark.SleepyMatt/.igtheme/Nord-Theme-Dark.SleepyMatt.igtheme

When you change the name of the path, please let me know to update IG website as well, otherwise, the download link will be broken.
